 const ADD_TO_CART='ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const CLEAR_ALL='CLEAR_ALL';
const CHANGE_QUANTITY='CHANGE_QUANTITY';
const ADD_PRODUCTS ='ADD_PRODUCTS';

export{
    ADD_TO_CART,
    REMOVE_FROM_CART,
    CHANGE_QUANTITY,
    CLEAR_ALL,
    ADD_PRODUCTS
}
